# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 23:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.BigIntegerField()),
                ('term', models.BigIntegerField()),
                ('users', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('passwd', models.TextField()),
                ('emailid', models.TextField()),
                ('phone', models.BigIntegerField()),
                ('courses', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None)),
            ],
        ),
    ]
