# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 09:40
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asuca', '0003_auto_20170626_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), null=True, size=None),
        ),
    ]
