# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 01:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asuca', '0005_auto_20170630_0628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
